### ISSUE TITLE
Error on /admin

### ISSUE THREAD

**Issue by mnshankar** [ultraplugin/magento2-chatgpt#1]
I get this error when trying to open the admin page after installing this plugin (I've followed all the usual directions for plugin install):

Exception #0 (Exception): Warning: Undefined array key "id" in /home/cloudpanel/htdocs/test.mag1.com/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

PHP 8.1
Magento 2.4.6 p1

Thanks!

**Comment by ecoprince** [comment]
Hi @mnshankar To resolve this issue, kindly install the UltraPlugin Base extension.

Ultraplugin base extension: https://github.com/ultraplugin/module-base

**Comment by ultraplugin** [comment]
Hi @mnshankar To resolve this issue, kindly install the UltraPlugin Base extension.

Ultraplugin Extension: https://github.com/ultraplugin/module-base
